version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=sqlite3:db/development.sqlite3
      - RAILS_ENV=development
      - RAILS_LOG_TO_STDOUT=true
    command: bundle exec rails s -p 3000 -b '0.0.0.0'